### ISSUE TITLE
Improve footnote rendering in tex

### ISSUE THREAD

**Issue by rowanc1** [executablebooks/mystjs#260]
Two things:

(1) there are two new lines after a footnote inline close. I think we can improve this a bit!
(2) We should raise and show errors in latex, e.g. when a reference to a foot note is not found!

![image](https://user-images.githubusercontent.com/913249/221058431-df32965a-463a-49ed-91bc-5c73a076f344.png)

Thoughts @fwkoch?

**Comment by fwkoch** [comment]
This PR fixes the trailing whitespace issue: https://github.com/executablebooks/mystjs/pull/277

It also adds warnings when a footnote definition is not found... _However_ - this case will not usually come up because the markdown-it parser does not parse references without definitions  - See this issue: https://github.com/executablebooks/mystjs/issues/278

**Comment by rowanc1** [comment]
The other issue is tackled here:
- https://github.com/executablebooks/myst-theme/pull/26

🚀  Thanks @fwkoch
